baseURL = "https://www.wegmueller.it/"
languageCode = "en-us"
title = "Toast's Personal Blog"
theme = "ananke"

[params]
  favicon = ""
  description = "a personal blog by Toast"
  facebook = ""
  twitter = "https://twitter.com/TheRealToaster"
  instagram = ""
  youtube = ""
  github = "https://github.com/Toasterson"
  linkedin = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/index.jpg"
